# fix data

In [20]:
import pandas as pd

In [32]:
gap = pd.read_csv('gapminder.csv')

In [33]:
new_p=[]
for p in gap["Population"]:
    char = p[-1]
    if char == "M":
        new_p.append(float(p[:-1])*1000000)
    elif char == "k":
        new_p.append(float(p[:-1])*1000)
    elif char == "B":
        new_p.append(float(p[:-1])*1000000000)
    else:
        new_p.append(float(p))
gap['new_pop']=new_p

In [34]:
gap

,Unnamed: 0,country,Year,Life-Expectancy,Population,geo,Income,GDP total,GDP per capita growth (%),new_pop
0,0,Afghanistan,1990,53.8,13.3M,afg,1119,1.389481e+10,-3.60,13300000.0
1,1,Afghanistan,1991,54.2,14.5M,afg,1024,1.362238e+10,-8.50,14500000.0
2,2,Afghanistan,1992,54.4,15.8M,afg,981,1.420976e+10,-4.23,15800000.0
3,3,Afghanistan,1993,53.9,17.1M,afg,672,1.063450e+10,-31.46,17100000.0
4,4,Afghanistan,1994,54.3,18.1M,afg,498,8.504078e+09,-25.93,18100000.0
...,...,...,...,...,...,...,...,...,...,...
5695,5695,Zimbabwe,2015,59.2,14M,zwe,3708,5.121948e+10,0.10,14000000.0
5696,5696,Zimbabwe,2016,59.9,14.2M,zwe,3678,5.160663e+10,-0.79,14200000.0
5697,5697,Zimbabwe,2017,60.6,14.4M,zwe,3796,5.403704e+10,3.19,14400000.0
5698,5698,Zimbabwe,2018,61.0,14.6M,zwe,3923,5.664390e+10,3.36,14600000.0
5699,5699,Zimbabwe,2019,60.7,14.9M,zwe,3630,5.316356e+10,-7.47,14900000.0